version: "3"
services:
  mysql:
    container_name: fastapi_admin_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    ports:
      - "33071:3306"

  redis:
    container_name: fastapi_admin_redis
    image: redis:latest
    ports:
      - "6379:6379"
